dataset:
  video_info_file: data/video_info_19993.json
  feat_dir: data/tsn_anet/all_csv_mean_100/
  tscale: 100
  feature_dim: 400

saver:
  root_dir: output
  checkpoint_dir: pretrained_model
  result_dir: result

testing:
  mode: validation
  # mode: testing
  batch_size: 16
